complete_from_path = true
ctrlc_exit = false
disable_table_indexes = false
filesize_format = "B"
filesize_metric = true
nonzero_exit_errors = true
path = [
    "/sbin", 
    "/bin", 
    "/usr/local/sbin", 
    "/usr/local/bin", 
    "/usr/sbin", 
    "/usr/bin", 
    "/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin", 
    "/Library/Apple/usr/bin", 
    "/opt/homebrew/opt/go/libexec/bin", 
    "/opt/homebrew/opt/sphinx-doc/bin", 
    "/opt/homebrew/opt/sqlite/bin", 
    "/opt/homebrew/opt/python/bin", 
    "/opt/homebrew/opt/macvim/bin", 
    "/opt/homebrew/opt/icu4c/bin", 
    "/opt/homebrew/opt/grep/bin", 
    "/opt/homebrew/opt/fzf/bin", 
    "/opt/homebrew/sbin", 
    "/opt/homebrew/bin", 
    "/opt/X11/bin", 
    "~/data/data/.runtime/customs/bin/ssh-auto-login/auto_gen", 
    "~/data/data/.runtime/customs/others/git-fuzzy/bin", 
    "~/.zinit/plugins/unixorn---git-extra-commands/bin", 
    "~/.zinit/plugins/paulirish---git-open", 
    "~/data/data/.runtime/customs/bin", 
    "~/Library/Python/3.9/bin", 
    "~/Library/Python/3.8/bin", 
    "~/.zinit/polaris/bin", 
    "~/.aliases.d/shims", 
    "~/go-develop/bin", 
    "~/.SpaceVim/bin", 
    "~/.local/bin", 
    "~/.yarn/bin", 
    "~/bin"
]
pivot_mode = "auto"
plugin_dirs = ["~/.nu-plugin-lib"]
prompt = "starship_prompt"
rm_always_trash = true
skip_welcome_message = false
startup = [
    "source ~/.nu/config/alias.config", 
    "source ~/.nu/config/func.config", 
    "mkdir ~/.cache/starship", 
    "/opt/homebrew/bin/starship init nu | save ~/.cache/starship/init.nu", 
    "source ~/.cache/starship/init.nu", 
    "source ~/.nu/config/env.config"
]
table_mode = "other"

[color_config]
header_align = "l"
header_bold = true
header_color = "c"
index_color = "rd"
leading_trailing_space_bg = "white"
primitive_binary = "cyan"
primitive_boolean = "green"
primitive_columnpath = "cyan"
primitive_date = "ru"
primitive_decimal = "red"
primitive_duration = "blue"
primitive_filesize = "ur"
primitive_int = "green"
primitive_line = "yellow"
primitive_path = "yellow"
primitive_pattern = "white"
primitive_range = "purple"
primitive_string = "pb"
separator_color = "purple"

[line_editor]
auto_add_history = true
bell_style = "audible"
color_mode = "enabled"
completion_prompt_limit = 100
completion_type = "circular"
edit_mode = "vim"
history_duplicates = "ignoreconsecutive"
history_ignore_space = false
keyseq_timeout_ms = 500
max_history_size = 100000
tab_stop = 4

[textview]
colored_output = true
grid = true
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen"
snip = true
tab_width = 4
term_width = "default"
theme = "TwoDark"
true_color = true
use_italics = true
vcs_modification_markers = true
wrapping_mode = "NoWrapping"
