LANGS = {
    "zh": {
        "bookshelf": "书架",
        "add_book": "添加小说",
        "add_dir": "添加目录",
        "progress": "进度",
        "bookmark": "书签",
        "help": "帮助",
        "exit": "退出",
        "setting": "设置",
        "search": "搜索",
        "stats": "阅读统计",
        "stats_all": "全部书籍阅读统计",
        "stats_time": "累计阅读时间",
        "stats_days": "阅读天数",
        "stats_daily": "每日统计",
        "read": "朗读",
        "chapter": "章节",
        "theme": "主题",
        "language": "语言",
        "current_page": "当前页",
        "auto_page": "自动翻页",
        "jump_chapter": "跳转章节",
        "author": "作者",
        "input_path": "输入文件路径：",
        "input_dir": "输入目录路径：",
        "input_search": "输入搜索关键词：",
        "input_comment": "输入书签备注：",
        "input_theme": "主题 (dark/light/eye)：",
        "input_lang": "语言 (zh/en)：",
        "input_font_color": "字体颜色(black/red/green/yellow/blue/magenta/cyan/white)：",
        "input_bg_color": "背景颜色(black/red/green/yellow/blue/magenta/cyan/white)：",
        "input_border_style": "边框样式(round/double/single/bold/none)：",
        "input_border_color": "边框颜色(black/red/green/yellow/blue/magenta/cyan/white)：",
        "input_jump_page": "输入页码并回车跳转：",
        "input_jump_page_quit": "输入页码并回车跳转, q退出",
        "bookmark_list": "书签列表",
        "input_remind_interval": "阅读提醒间隔(分钟, 0为关闭)：",
        "remind_msg": "您已阅读{minutes}分钟了，休息一下眼睛吧！",
        "invalid": "无效输入",
        "pre_page": "上一页",
        "next_page": "下一页",
        "delete": "删除",
        "move": "移动",
        "select": "选择",
        "tag": "标签",
        "input_no": "输入序号",
        "no_unlimited": "序号超范围！",
        "wait_for_loading":"请稍候，正在努力加载",
        "loading": "加载中",
        "novel_reader": "小说阅读器",
        "number": "序号",
        "minutes": "分钟",
        "day": "天",
        "back": "返回",
        "page_no": "第{page}页",
        "book_deletion_title": "删除书籍 - 空格选择/取消, Enter确认删除, q返回",
        "book_deletion_help": "[↑↓]移动 [空格]选择/取消 [n]下一页 [p]上一页 [a]全选 [c]取消全选 [Enter]删除选中 [q]返回",
        "book_deletion_confirm": "确认删除 {books} 本书籍?",
        "book_deletion_success": "已成功删除 {books} 本书籍",
        "reading_progress": "阅读进度",
        "empty_file_or_cannot_read": "文件为空或无法解析内容",
        "aloud_r2_stop": "朗读中 - 按r停止",
        "books": "书籍",
        "unfind_type_new": "未找到，请输入新路径",
        "update_path_success": "路径更新成功!",
        "update_path_fail": "路径更新失败!",
        "path_not_exists": "路径无效或文件不存在!",
        "terminal_help_text": "按空格+回车返回 | ↑↓浏览历史命令",
        "terminal_title": "终端模式",
        "terminal_help_text2": "使用空格+回车退出终端模式",
        "command_exists_code": "命令退出代码",
        "command_time_unlimit": "命令执行超时",
        "execute_fail": "执行错误",
        "terminal_mode_started": "终端模拟器已启动",
        "file_not_exists": "文件不存在",
        "cannot_load_novel": "无法加载小说",
        "empty_directory_or_file": "空文件或文件内容为空",
        "action_document_line": "处理文本行",
        "action_document_file": "处理文本内容",
        "action_pages": "分页处理",
        "reading_from_file": "读取文件内容",
        "loading_books": "加载书籍中",
        "parsing_epub_data": "解析EPUB元数据",
        "save_to_db": "保存到数据库",
        "total_add_books": "添加目录中的书籍，共 {books} 本",
        "parsing_books": "处理第 {books} 本",
        "tag_management": "标签管理",
        "edit_book": "编辑书籍",
        "add_tag": "添加标签",
        "remove_tag": "删除标签",
        "filter_by_tag": "按标签筛选",
        "batch_edit": "批量编辑",
        "edit_title": "编辑标题",
        "edit_author": "编辑作者",
        "edit_tags": "编辑标签",
        "save_changes": "保存更改",
        "tag_already_exists": "标签已存在",
        "tag_added": "标签已添加",
        "tag_removed": "标签已移除",
        "no_tags": "无标签",
        "tag_mode": "标签模式: 使用空格选择/取消标签，Enter确认",
        "switch_tag_mode":"切换标签模式",
        "confirm":"确认",
        "multype_tags_edit_books": "批量标签编辑 ({books}) 本书",
        "out_multype_mode": "退出多选模式",
        "in_multype_mode": "进入多选模式",
        "space": "空格",
        "select_or_unselect": "选择/取消",
        "multype_tags_edit": "批量编辑标签",
        "select_all": "全选",
        "unselect_all": "取消全选",
        "multype_mode": "多选模式",
        "already_selected_books": "已选 {books} 本",
        "use_filter": "应用筛选",
        "type_new_tag_name": "输入新标签名称",
        "type_tag_name": "输入标签名称",
        "clear_input": "清除输入",
        "type_anykey_or_quit": "按任意键继续编辑，按q返回",
        "already_deleted_tag": "已删除标签",
        "remove_tag_failed": "删除标签失败",
        "confirm_remove_tags": "确认删除标签",
        "edit_book_info": "编辑书籍信息",
        "book_name": "书名",
        "book_author": "作者",
        "new_book_name": "新书名",
        "new_book_author": "新作者",
        "new_book_tags": "新标签(逗号分隔)",
        "already_success_books": "已为 {books} 本书",
        "update_books_source_failed": "更新书籍元数据失败",
        "not_exists": "不存在",
        "cannot_create_tag": "无法创建或获取标签 '{tag}' 的ID",
        "multype_update_success": "批量更新完成",
        "multype_update_failed": "批量更新失败",
        "update_success_books": "成功更新 {count} 本书籍",
        "deal_book_id_error": "处理书籍 {id} 时出错",
        "auto_complete": "自动补全",
        "clear_screen": "清屏",
    },
    "en": {
        "bookshelf": "Bookshelf",
        "add_book": "Add Book",
        "add_dir": "Add Directory",
        "progress": "Progress",
        "bookmark": "Bookmark",
        "help": "Help",
        "exit": "Exit",
        "setting": "Settings",
        "search": "Search",
        "stats": "Reading Stats",
        "stats_all": "All Books Stats",
        "stats_time": "Total Reading Time",
        "stats_days": "Reading Days",
        "stats_daily": "Daily Stats",
        "read": "Read Aloud",
        "chapter": "Chapter",
        "theme": "Theme",
        "language": "Language",
        "current_page": "Page",
        "auto_page": "Auto Page",
        "jump_chapter": "Jump Chapter",
        "author": "Author",
        "input_path": "Input file path:",
        "input_dir": "Input directory path:",
        "input_search": "Input search keyword:",
        "input_comment": "Input bookmark comment:",
        "input_theme": "Theme (dark/light/eye):",
        "input_lang": "Language (zh/en):",
        "input_font_color": "Font color (black/red/green/yellow/blue/magenta/cyan/white):",
        "input_bg_color": "Background color (black/red/green/yellow/blue/magenta/cyan/white):",
        "input_border_style": "Border style (round/double/single/bold/none):",
        "input_border_color": "Border color (black/red/green/yellow/blue/magenta/cyan/white):",
        "input_jump_page": "Input page number and press Enter to jump:",
        "input_jump_page_quit": "Input page number and press Enter to jump, press q to quit",
        "bookmark_list": "Bookmark List",
        "input_remind_interval": "Reading reminder interval (minutes, 0=off):",
        "remind_msg": "You've been reading for {minutes} minutes, please rest your eyes!",
        "invalid": "Invalid input",
        "pre_page": "Previous",
        "next_page": "Next",
        "delete": "Delete",
        "move": "Move",
        "select": "Select",
        "tag": "Tag",
        "input_no": "Input number",
        "no_unlimited": "The number is out of limit！",
        "wait_for_loading":"Please wait for Loading",
        "loading": "Loading",
        "novel_reader": "Novel Reader",
        "number": "NO",
        "minutes": "minites",
        "day": "day",
        "back": "Back",
        "page_no": "page {page}",
        "book_deletion_title": "Book deletion - space to select/unselect, Enter to delete, q to quit",
        "book_deletion_help": "[↑↓] Move [space] Select/Unselect [n] Next page [p] Previous page [a] Select all [c] Unselect all [Enter] Delete [q] Back",
        "book_deletion_confirm": "Confirm to delete {books} books ?",
        "book_deletion_success": "delete {books} books success",
        "reading_progress": "reading progress",
        "empty_file_or_cannot_read": "empty file or can not read",
        "aloud_r2_stop": "Read aloud - Press r to stop",
        "books": "Books",
        "unfind_type_new": "Can not find，Please type new path",
        "update_path_success": "Update path successs!",
        "update_path_fail": "Update path failed!",
        "path_not_exists": "Path invalid or file does not exists!",
        "terminal_help_text": "Press Space + Enter to back | ↑↓ Show history command",
        "terminal_title": "Terminal Mode",
        "terminal_help_text2": "Press Space + Enter to quit",
        "command_exists_code": "Command exists code",
        "command_time_unlimit": "Command timeout",
        "execute_fail": "Execution Error",
        "terminal_mode_started": "Terminal mode started",
        "file_not_exists": "File does not exists",
        "cannot_load_novel": "Load novel failed",
        "empty_directory_or_file": "Empty directory or file",
        "action_document_line": "Dealing with document lines",
        "action_document_file": "Dealing with document files",
        "action_pages": "Dealing with pages",
        "reading_from_file": "Reading from file",
        "loading_books": "Loadding books",
        "parsing_epub_data": "Parsing EPUB metadata",
        "save_to_db": "Save to database",
        "total_add_books": "Total books in path is {books}",
        "parsing_books": "Parsing books {books}",
        "tag_mode": "Tag mode: Press space to select/unselect，Enter to confirm",
        "tag_management": "Tag Management",
        "edit_book": "Edit Book",
        "add_tag": "Add Tag",
        "remove_tag": "Remove Tag",
        "filter_by_tag": "Filter by Tag",
        "batch_edit": "Batch Edit",
        "edit_title": "Edit Title",
        "edit_author": "Edit Author",
        "edit_tags": "Edit Tags",
        "save_changes": "Save Changes",
        "tag_already_exists": "Tag already exists",
        "tag_added": "Tag added",
        "tag_removed": "Tag removed",
        "no_tags": "No tags",
        "switch_tag_mode":"Switch tag mode",
        "confirm":"Confirm",
        "multype_tags_edit_books": "Multype tags edit books ({books})",
        "out_multype_mode": "Multype mode exists",
        "in_multype_mode": "Into multype mode",
        "space": "Space",
        "select_or_unselect": "Select/Unselect",
        "multype_tags_edit": "Multype edit tags",
        "select_all": "Select All",
        "unselect_all": "Unselect All",
        "multype_mode": "Multype Mode",
        "already_selected_books": "Selected {books}",
        "use_filter": "Use filter",
        "type_new_tag_name": "Type new tag name",
        "type_tag_name": "Type tag name",
        "clear_input":"Clear input",
        "type_anykey_or_quit":"Type any key to continue or q to quit",
        "already_deleted_tag": "Tags already deleted",
        "remove_tag_failed": "Remove tag failed",
        "confirm_remove_tags": "Confirm to remove tags",
        "edit_book_info": "Edit book infomation",
        "book_name": "Book name",
        "book_author": "Author",
        "new_book_name": "New book name",
        "new_book_author": "New author",
        "new_book_tags": "New tags (Separate with ,)",
        "already_success_books": "Already {books} books ",
        "update_books_source_failed": "Update books source failed",
        "not_exists": "Does not exists",
        "cannot_create_tag": "Can not create or get {tag} ID",
        "multype_update_success": "Multype update success",
        "multype_update_failed": "Multype update failed",
        "update_success_books": "Updated success books {count}",
        "deal_book_id_error": "Deal with book {id} error",
        "auto_complete": "Auto complete",
        "clear_screen": "Clear screen",
    }
}

def get_text(key, lang="zh"):
    return LANGS.get(lang, LANGS["zh"]).get(key, key)