LANGS = {
    "zh": {
        "bookshelf": "书架",
        "add_book": "添加小说",
        "add_dir": "添加目录",
        "progress": "进度",
        "bookmark": "书签",
        "help": "帮助",
        "exit": "退出",
        "setting": "设置",
        "search": "搜索",
        "stats": "阅读统计",
        "stats_all": "全部书籍阅读统计",
        "stats_time": "累计阅读时间",
        "stats_days": "阅读天数",
        "stats_daily": "每日统计",
        "read": "朗读",
        "chapter": "章节",
        "theme": "主题",
        "language": "语言",
        "current_page": "当前页",
        "auto_page": "自动翻页",
        "jump_chapter": "跳转章节",
        "author": "作者",
        "input_path": "输入文件路径：",
        "input_dir": "输入目录路径：",
        "input_search": "输入搜索关键词：",
        "input_comment": "输入书签备注：",
        "input_theme": "主题 (dark/light/eye/midnight/sepia/forest/amethyst/ocean/crimson/slate/transparent-dark/transparent-light/transparent-blue)：",
        "input_lang": "语言 (zh/en)：",
        "input_font_color": "字体颜色(black/red/green/yellow/blue/magenta/cyan/white)：",
        "input_bg_color": "背景颜色(black/red/green/yellow/blue/magenta/cyan/white/transparent)：",
        "input_border_style": "边框样式(round/double/single/bold/dotted/dashed/curved/thick/shadow/fancy/minimal/classic/none)：",
        "input_border_color": "边框颜色(black/red/green/yellow/blue/magenta/cyan/white)：",
        "input_jump_page": "输入页码并回车跳转：",
        "input_jump_page_quit": "输入页码并回车跳转, q退出",
        "bookmark_list": "书签列表",
        "input_remind_interval": "阅读提醒间隔(分钟, 0为关闭)：",
        "remind_msg": "您已阅读{minutes}分钟了，休息一下眼睛吧！",
        "invalid": "无效输入",
        "pre_page": "上一页",
        "next_page": "下一页",
        "delete": "删除",
        "move": "移动",
        "select": "选择",
        "tag": "标签",
        "input_no": "输入序号",
        "no_unlimited": "序号超范围！",
        "wait_for_loading":"请稍候，正在努力加载",
        "loading": "加载中",
        "novel_reader": "小说阅读器",
        "number": "序号",
        "minutes": "分钟",
        "day": "天",
        "back": "返回",
        "page_no": "第{page}页",
        "book_deletion_title": "删除书籍 - 空格选择/取消, Enter确认删除, q返回",
        "book_deletion_help": "[↑↓]移动 [空格]选择/取消 [n]下一页 [p]上一页 [a]全选 [c]取消全选 [Enter]删除选中 [q]返回",
        "book_deletion_confirm": "确认删除 {books} 本书籍?",
        "book_deletion_success": "已成功删除 {books} 本书籍",
        "reading_progress": "阅读进度",
        "empty_file_or_cannot_read": "文件为空或无法解析内容",
        "aloud_r2_stop": "朗读中 - 按r停止",
        "books": "书籍",
        "unfind_type_new": "未找到，请输入新路径",
        "update_path_success": "路径更新成功!",
        "update_path_fail": "路径更新失败!",
        "path_not_exists": "路径无效或文件不存在!",
        "terminal_help_text": "按空格+回车返回 | ↑↓浏览历史命令",
        "terminal_title": "终端模式",
        "terminal_help_text2": "使用空格+回车退出终端模式",
        "command_exists_code": "命令退出代码",
        "command_time_unlimit": "命令执行超时",
        "execute_fail": "执行错误",
        "terminal_mode_started": "终端模拟器已启动",
        "file_not_exists": "文件不存在",
        "cannot_load_novel": "无法加载小说",
        "empty_directory_or_file": "空文件或文件内容为空",
        "action_document_line": "处理文本行",
        "action_document_file": "处理文本内容",
        "action_pages": "分页处理",
        "reading_from_file": "读取文件内容",
        "loading_books": "加载书籍中",
        "parsing_epub_data": "解析EPUB元数据",
        "parsing_pdf_data": "解析PDF数据",
        "parsing_mobi_data": "解析MOBI数据",
        "parsing_azw_data": "解析AZW数据",
        "parsing_data_outtime": "解析超时",
        "save_to_db": "保存到数据库",
        "total_add_books": "添加目录中的书籍，共 {books} 本",
        "parsing_books": "处理第 {books} 本",
        "tag_management": "标签管理",
        "edit_book": "编辑书籍",
        "add_tag": "添加标签",
        "remove_tag": "删除标签",
        "filter_by_tag": "按标签筛选",
        "batch_edit": "批量编辑",
        "edit_title": "编辑标题",
        "edit_author": "编辑作者",
        "edit_tags": "编辑标签",
        "save_changes": "保存更改",
        "tag_already_exists": "标签已存在",
        "tag_added": "标签已添加",
        "tag_removed": "标签已移除",
        "no_tags": "无标签",
        "tag_mode": "标签模式: 使用空格选择/取消标签，Enter确认",
        "switch_tag_mode":"切换标签模式",
        "confirm":"确认",
        "multype_tags_edit_books": "批量标签编辑 ({books}) 本书",
        "out_multype_mode": "退出多选模式",
        "in_multype_mode": "进入多选模式",
        "space": "空格",
        "select_or_unselect": "选择/取消",
        "multype_tags_edit": "批量编辑标签",
        "select_all": "全选",
        "unselect_all": "取消全选",
        "multype_mode": "多选模式",
        "already_selected_books": "已选 {books} 本",
        "use_filter": "应用筛选",
        "type_new_tag_name": "输入新标签名称",
        "type_tag_name": "输入标签名称",
        "clear_input": "清除输入",
        "type_anykey_or_quit": "按任意键继续编辑，按q返回",
        "already_deleted_tag": "已删除标签",
        "remove_tag_failed": "删除标签失败",
        "confirm_remove_tags": "确认删除标签",
        "edit_book_info": "编辑书籍信息",
        "book_name": "书名",
        "book_author": "作者",
        "new_book_name": "新书名",
        "new_book_author": "新作者",
        "new_book_tags": "新标签(逗号分隔)",
        "already_success_books": "已为 {books} 本书",
        "update_books_source_failed": "更新书籍元数据失败",
        "not_exists": "不存在",
        "cannot_create_tag": "无法创建或获取标签 '{tag}' 的ID",
        "multype_update_success": "批量更新完成",
        "multype_update_failed": "批量更新失败",
        "update_success_books": "成功更新 {count} 本书籍",
        "deal_book_id_error": "处理书籍 {id} 时出错",
        "auto_complete": "自动补全",
        "clear_screen": "清屏",
        "edit": "编辑",
        "jump": "跳转",
        "none_bookmark": "暂无书签",
        "press_anykey_back": "按任意键返回",
        "edit_bookmark_comment": "编辑书签备注",
        "confirm_delete_bookmark": "确认删除书签",
        "enter_confirm_q_back": "回车修改，q返回",
        "new_val": "新值",
        "setting_page": "设置界面",
        "statusbar_switch": "状态栏显示",
        "speech_rate": "朗读语速",
        "auto_pager_sec": "自动翻页秒",
        "line_spacing": "行距",
        "width": "宽度",
        "height": "高度",
        "current_dir": "当前目录",
        "help_center": "帮助中心",
        "press_anykey_back_reading": "按任意键返回阅读界面",
        "press_q_back_reading": "按q键返回阅读界面",
        "novel": "小说",
        "press_anykey_back_r_rich": "按任意键返回，按[R]查看Rich统计图表",
        "r_view_all_charts": "按[R]查看所有书籍的Rich统计图表",
        "none_stats": "暂无统计数据",
        "total": "总计",
        "avg": "平均",
        "cycle": "周期",
        "cycle_count": "周期数",
        "press_enter_to_back": "按回车键返回",
        "daily_stats": "每日阅读时间",
        "weekly_stats": "每周阅读时间",
        "monthly_stats": "每月阅读时间",
        "hours": "小时",
        "switch_unit": "切换单位",
        "day_view": "日视图",
        "week_view": "周视图",
        "month_view": "月视图",
        "nearly_ten_days": "最近10天",
        "nearly_eight_weeks": "最近8周",
        "nearly_tweleve_month": "最近12个月",
        "date": "日期",
        "reading_time_minutes": "阅读时间(分钟)",
        "chart": "图表",
        "none_data": "暂无数据",
        "week": "周次",
        "month": "月份",
        "days": "天数",
        "highest": "最高",
        "lowest": "最低",
        "every_day_stats": "每日统计摘要",
        "help_t1": "阅读控制",
        "help_t2": "书签功能",
        "help_t3": "朗读功能",
        "help_t4": "书籍管理",
        "help_t5": "统计信息",
        "help_t6": "老板键功能",
        "help_t7": "系统操作",
        "help_t1_a": "自动翻页",
        "help_t1_g": "跳转到指定页",
        "help_t1_line": "搜索文本",
        "help_t2_b": "添加书签",
        "help_t2_bigb": "查看书签列表",
        "help_t3_r": "开始/停止朗读",
        "help_t4_m": "返回书架",
        "help_t4_s": "设置选项",
        "help_t5_t": "本书阅读统计",
        "help_t5_bigt": "全部书籍统计",
        "help_t5_bigr": "Rich版本的阅读统计",
        "help_t6_key_space": "空格键",
        "help_t6_key_space_desc": "隐藏/显示阅读器",
        "help_t6_key_space_enter": "空格+回车",
        "help_t6_key_space_enter_desc": "从终端返回阅读器",
        "help_t6_key_move_desc": "浏览命令历史",
        "help_t7_ask": "显示帮助",
        "help_t7_q": "退出程序",
        "help_key_page": "←/→/PgUp/PgDn/j/k 翻页",
        "help_key_auto_page": "a 自动翻页",
        "help_key_add_bookmark": "b 添加书签",
        "help_key_bookmark_list": "B 书签列表",
        "help_key_jump_page": "g 跳页",
        "help_key_bookshelf": "m 书架",
        "help_key_settings": "s 设置",
        "help_key_read_aloud": "r 朗读/停止",
        "help_key_search": "/ 搜索",
        "help_key_help": "? 帮助",
        "help_key_exit": "q 退出",
        "help_key_stats": "t 阅读统计",
        "help_key_all_stats": "T 全部统计",
        "help_key_delete_book": "x 删除书籍",
        "help_key_boss_key": "空格 老板键",
        "recent_books": "最近阅读",
        "font_settings": "字体设置",
        "font_size_relative": "字体缩放",
        "font_scale_desc": "调整字体显示大小比例",
        "line_spacing_desc": "调整行与行之间的间距",
        "paragraph_spacing_desc": "调整段落与段落之间的间距",
        "font_presets": "字体预设方案",
        "font_preset_small": "小字体",
        "font_preset_standard": "标准字体",
        "font_preset_large": "大字体",
        "font_preset_comfort": "舒适阅读",
        "font_preset_compact": "紧凑排版",
        "preview": "预览",
        "settings_applied": "设置已应用",
        "font_settings_applied": "字体设置已应用",
        "font_settings_auto_adjusted": "字体设置已根据屏幕尺寸自动调整",
        "auto_adjust": "自动调整",
        "font_scale": "字体缩放",
        "line_spacing_setting": "行距设置",
        "paragraph_spacing_setting": "段距设置",
        "current_value": "当前值",
        "increase": "增大",
        "decrease": "减小",
        "apply": "应用",
        "cancel": "取消",
        "custom_settings": "自定义设置",
        "recent_books_short": "最近",
        "adjust": "调整",
        "get_screen_size": "检测到屏幕尺寸",
        "recommend_use": "推荐使用",
        "cannot_be_less_than": "不能小于",
        "cannot_be_greater_than": "不能大于",
        "more_lines": "更多行",
        "content_outside_warning": "部分内容超出屏幕:",
        "lines": "行",
        "chars": "字符",
        "reset_position": "重置显示位置",
        "reset": "重置",
        "turn_page": "翻页",
        "on": "开",
        "off": "关",
        "yes": "是",
        "no": "否",
        "window_size_warnning": "终端窗口太小，请调整大小后重试",
    },
    "en": {
        "bookshelf": "Bookshelf",
        "add_book": "Add Book",
        "add_dir": "Add Directory",
        "progress": "Progress",
        "bookmark": "Bookmark",
        "help": "Help",
        "exit": "Exit",
        "setting": "Settings",
        "search": "Search",
        "stats": "Reading Stats",
        "stats_all": "All Books Stats",
        "stats_time": "Total Reading Time",
        "stats_days": "Reading Days",
        "stats_daily": "Daily Stats",
        "read": "Read Aloud",
        "chapter": "Chapter",
        "theme": "Theme",
        "language": "Language",
        "current_page": "Page",
        "auto_page": "Auto Page",
        "jump_chapter": "Jump Chapter",
        "author": "Author",
        "input_path": "Input file path:",
        "input_dir": "Input directory path:",
        "input_search": "Input search keyword:",
        "input_comment": "Input bookmark comment:",
        "input_theme": "Theme (dark/light/eye/midnight/sepia/forest/amethyst/ocean/crimson/slate/transparent-dark/transparent-light/transparent-blue):",
        "input_lang": "Language (zh/en):",
        "input_font_color": "Font color (black/red/green/yellow/blue/magenta/cyan/white):",
        "input_bg_color": "Background color (black/red/green/yellow/blue/magenta/cyan/white/transparent):",
        "input_border_style": "Border style (round/double/single/bold/none):",
        "input_border_color": "Border color (black/red/green/yellow/blue/magenta/cyan/white):",
        "input_jump_page": "Input page number and press Enter to jump:",
        "input_jump_page_quit": "Input page number and press Enter to jump, press q to quit",
        "bookmark_list": "Bookmark List",
        "input_remind_interval": "Reading reminder interval (minutes, 0=off):",
        "remind_msg": "You've been reading for {minutes} minutes, please rest your eyes!",
        "invalid": "Invalid input",
        "pre_page": "Previous",
        "next_page": "Next",
        "delete": "Delete",
        "move": "Move",
        "select": "Select",
        "tag": "Tag",
        "input_no": "Input number",
        "no_unlimited": "The number is out of limit！",
        "wait_for_loading":"Please wait for Loading",
        "loading": "Loading",
        "novel_reader": "Novel Reader",
        "number": "NO",
        "minutes": "minites",
        "day": "day",
        "back": "Back",
        "page_no": "page {page}",
        "book_deletion_title": "Book deletion - space to select/unselect, Enter to delete, q to quit",
        "book_deletion_help": "[↑↓] Move [space] Select/Unselect [n] Next page [p] Previous page [a] Select all [c] Unselect all [Enter] Delete [q] Back",
        "book_deletion_confirm": "Confirm to delete {books} books ?",
        "book_deletion_success": "delete {books} books success",
        "reading_progress": "reading progress",
        "empty_file_or_cannot_read": "empty file or can not read",
        "aloud_r2_stop": "Read aloud - Press r to stop",
        "books": "Books",
        "unfind_type_new": "Can not find，Please type new path",
        "update_path_success": "Update path successs!",
        "update_path_fail": "Update path failed!",
        "path_not_exists": "Path invalid or file does not exists!",
        "terminal_help_text": "Press Space + Enter to back | ↑↓ Show history command",
        "terminal_title": "Terminal Mode",
        "terminal_help_text2": "Press Space + Enter to quit",
        "command_exists_code": "Command exists code",
        "command_time_unlimit": "Command timeout",
        "execute_fail": "Execution Error",
        "terminal_mode_started": "Terminal mode started",
        "file_not_exists": "File does not exists",
        "cannot_load_novel": "Load novel failed",
        "empty_directory_or_file": "Empty directory or file",
        "action_document_line": "Dealing with document lines",
        "action_document_file": "Dealing with document files",
        "action_pages": "Dealing with pages",
        "reading_from_file": "Reading from file",
        "loading_books": "Loadding books",
        "parsing_epub_data": "Parsing EPUB metadata",
        "parsing_pdf_data": "Parsing PDF metadata",
        "parsing_mobi_data": "Parsing MOBI metadata",
        "parsing_azw_data": "Parsing AZW metadata",
        "parsing_data_outtime": "Parsing metadata out of time",
        "save_to_db": "Save to database",
        "total_add_books": "Total books in path is {books}",
        "parsing_books": "Parsing books {books}",
        "tag_mode": "Tag mode: Press space to select/unselect，Enter to confirm",
        "tag_management": "Tag Management",
        "edit_book": "Edit Book",
        "add_tag": "Add Tag",
        "remove_tag": "Remove Tag",
        "filter_by_tag": "Filter by Tag",
        "batch_edit": "Batch Edit",
        "edit_title": "Edit Title",
        "edit_author": "Edit Author",
        "edit_tags": "Edit Tags",
        "save_changes": "Save Changes",
        "tag_already_exists": "Tag already exists",
        "tag_added": "Tag added",
        "tag_removed": "Tag removed",
        "no_tags": "No tags",
        "switch_tag_mode":"Switch tag mode",
        "confirm":"Confirm",
        "multype_tags_edit_books": "Multype tags edit books ({books})",
        "out_multype_mode": "Multype mode exists",
        "in_multype_mode": "Into multype mode",
        "space": "Space",
        "select_or_unselect": "Select/Unselect",
        "multype_tags_edit": "Multype edit tags",
        "select_all": "Select All",
        "unselect_all": "Unselect All",
        "multype_mode": "Multype Mode",
        "already_selected_books": "Selected {books}",
        "use_filter": "Use filter",
        "type_new_tag_name": "Type new tag name",
        "type_tag_name": "Type tag name",
        "clear_input":"Clear input",
        "type_anykey_or_quit":"Type any key to continue or q to quit",
        "already_deleted_tag": "Tags already deleted",
        "remove_tag_failed": "Remove tag failed",
        "confirm_remove_tags": "Confirm to remove tags",
        "edit_book_info": "Edit book infomation",
        "book_name": "Book name",
        "book_author": "Author",
        "new_book_name": "New book name",
        "new_book_author": "New author",
        "new_book_tags": "New tags (Separate with ,)",
        "already_success_books": "Already {books} books ",
        "update_books_source_failed": "Update books source failed",
        "not_exists": "Does not exists",
        "cannot_create_tag": "Can not create or get {tag} ID",
        "multype_update_success": "Multype update success",
        "multype_update_failed": "Multype update failed",
        "update_success_books": "Updated success books {count}",
        "deal_book_id_error": "Deal with book {id} error",
        "auto_complete": "Auto complete",
        "clear_screen": "Clear screen",
        "edit": "Edit",
        "jump": "Jump",
        "none_bookmark": "No bookmark data",
        "press_anykey_back": "Press any key to return",
        "edit_bookmark_comment": "Edit bookmark comment",
        "confirm_delete_bookmark": "Confirm to remove bookmark",
        "enter_confirm_q_back": "Press enter to edit, q to back",
        "new_val": "New value",
        "setting_page": "Setting page",
        "statusbar_switch": "Status bar switcher",
        "speech_rate": "Speech rate",
        "auto_pager_sec": "Auto pager seconds",
        "line_spacing": "Line spacing",
        "current_dir": "Current directory",
        "help_center": "Help Center",
        "press_anykey_back_reading": "Press any key to back reading page",
        "press_q_back_reading": "Press key q to back reading page",
        "novel": "Novel",
        "press_anykey_back_r_rich": "Press any key to back，[R] to view Rich Chart",
        "r_view_all_charts": "Press [R] to view all books Rich Charts",
        "none_stats": "None stats data",
        "total": "Total",
        "avg": "Avg",
        "cycle": "Cycle",
        "cycle_count": "Cycle count",
        "press_enter_to_back": "Press enter to back",
        "daily_stats": "Every day reading time",
        "weekly_stats": "Every week reading time",
        "monthly_stats": "Every month reading time",
        "hours": "Hours",
        "switch_unit": "Switch unit",
        "day_view": "Day view",
        "week_view": "Week view",
        "month_view": "Month view",
        "nearly_ten_days": "Nearly 10 days",
        "nearly_eight_weeks": "Nearly 8 weeks",
        "nearly_tweleve_month": "Nearly 12 monthes",
        "date": "Date",
        "reading_time_minutes": "Reading time (minutes)",
        "chart": "Chart",
        "none_data": "No data",
        "week": "Weekly",
        "month": "Month",
        "days": "Days",
        "highest": "Highest",
        "lowest": "Lowest",
        "every_day_stats": "Everyday stats",
        "help_t1": "Reading",
        "help_t2": "Bookmark",
        "help_t3": "Aloud",
        "help_t4": "Books",
        "help_t5": "Stats",
        "help_t6": "Bosskey",
        "help_t7": "System",
        "help_t1_a": "Auto pager",
        "help_t1_g": "Goto page",
        "help_t1_line": "Search",
        "help_t2_b": "Add bookmark",
        "help_t2_bigb": "View bookmark",
        "help_t3_r": "Start/Stop aloud",
        "help_t4_m": "Back to bookshelf",
        "help_t4_s": "Settings",
        "help_t5_t": "Book stats",
        "help_t5_bigt": "All Books Stats",
        "help_t5_bigr": "Rich Stats",
        "help_t6_key_space": "Space",
        "help_t6_key_space_desc": "Hide/Show Reader",
        "help_t6_key_space_enter": "Space+Enter",
        "help_t6_key_space_enter_desc": "From terminal back to reader",
        "help_t6_key_move_desc": "View command history",
        "help_t7_ask": "Show help",
        "help_t7_q": "Quit",
        "help_key_page": "←/→/PgUp/PgDn/j/k Page",
        "help_key_auto_page": "a Auto page",
        "help_key_add_bookmark": "b Add bookmark",
        "help_key_bookmark_list": "B Bookmark list",
        "help_key_jump_page": "g Jump page",
        "help_key_bookshelf": "m Bookshelf",
        "help_key_settings": "s Settings",
        "help_key_read_aloud": "r Read aloud/Stop",
        "help_key_search": "/ Search",
        "help_key_help": "? Help",
        "help_key_exit": "q Exit",
        "help_key_stats": "t Reading stats",
        "help_key_all_stats": "T All stats",
        "help_key_delete_book": "x Delete book",
        "help_key_boss_key": "Space Boss key",
        "recent_books": "Recently Read",
        "font_settings": "Font Settings",
        "font_size_relative": "Font Scale",
        "font_scale_desc": "Adjust font display scale",
        "line_spacing_desc": "Adjust spacing between lines",
        "paragraph_spacing_desc": "Adjust spacing between paragraphs",
        "font_presets": "Font Presets",
        "font_preset_small": "Small Font",
        "font_preset_standard": "Standard Font",
        "font_preset_large": "Large Font",
        "font_preset_comfort": "Comfort Reading",
        "font_preset_compact": "Compact Layout",
        "preview": "Preview",
        "settings_applied": "Settings Applied",
        "font_settings_applied": "Font settings applied",
        "font_settings_auto_adjusted": "Font settings auto-adjusted for screen size",
        "auto_adjust": "Auto Adjust",
        "font_scale": "Font Scale",
        "line_spacing_setting": "Line Spacing",
        "paragraph_spacing_setting": "Paragraph Spacing",
        "current_value": "Current Value",
        "increase": "Increase",
        "decrease": "Decrease",
        "apply": "Apply",
        "cancel": "Cancel",
        "custom_settings": "Custom Settings",
        "recent_books_short": "Recent",
        "adjust": "Adjust",
        "recommend_use": "Recommend",
        "cannot_be_less_than": "cannot be less than",
        "cannot_be_greater_than": "cannot be greater than",
        "more_lines": "more lines",
        "content_outside_warning": "Some content is outside screen:",
        "lines": "lines",
        "chars": "chars",
        "reset_position": "Reset position",
        "reset": "Reset",
        "turn_page": "Turn Page",
        "on": "ON",
        "off": "OFF",
        "yes": "Yes",
        "no": "No",
        "window_size_warnning": "Terminal Window is too small, Please adjust and try again",
    }
}

def get_text(key, lang="zh"):
    return LANGS.get(lang, LANGS["zh"]).get(key, key)