LANGS = {
    "zh": {
        "bookshelf": "书架",
        "add_book": "添加小说",
        "add_dir": "添加目录",
        "progress": "进度",
        "bookmark": "书签",
        "help": "帮助",
        "exit": "退出",
        "setting": "设置",
        "search": "搜索",
        "read": "朗读",
        "chapter": "章节",
        "theme": "主题",
        "language": "语言",
        "current_page": "当前页",
        "auto_page": "自动翻页",
        "jump_chapter": "跳转章节",
        "author": "作者",
        "input_path": "输入文件路径：",
        "input_dir": "输入目录路径：",
        "input_search": "输入搜索关键词：",
        "input_comment": "输入书签备注：",
        "input_theme": "主题 (dark/light/eye)：",
        "input_lang": "语言 (zh/en)：",
        "input_font_color": "字体颜色(black/red/green/yellow/blue/magenta/cyan/white)：",
        "input_bg_color": "背景颜色(black/red/green/yellow/blue/magenta/cyan/white)：",
        "input_border_style": "边框样式(round/double/single/bold/none)：",
        "input_border_color": "边框颜色(black/red/green/yellow/blue/magenta/cyan/white)：",
        "input_jump_page": "输入页码并回车跳转：",
        "bookmark_list": "书签列表",
        "input_remind_interval": "阅读提醒间隔(分钟, 0为关闭)：",
        "remind_msg": "您已阅读{minutes}分钟了，休息一下眼睛吧！",
        "invalid": "无效输入"
    },
    "en": {
        "bookshelf": "Bookshelf",
        "add_book": "Add Book",
        "add_dir": "Add Directory",
        "progress": "Progress",
        "bookmark": "Bookmark",
        "help": "Help",
        "exit": "Exit",
        "setting": "Settings",
        "search": "Search",
        "read": "Read Aloud",
        "chapter": "Chapter",
        "theme": "Theme",
        "language": "Language",
        "current_page": "Page",
        "auto_page": "Auto Page",
        "jump_chapter": "Jump Chapter",
        "author": "Author",
        "input_path": "Input file path:",
        "input_dir": "Input directory path:",
        "input_search": "Input search keyword:",
        "input_comment": "Input bookmark comment:",
        "input_theme": "Theme (dark/light/eye):",
        "input_lang": "Language (zh/en):",
        "input_font_color": "Font color (black/red/green/yellow/blue/magenta/cyan/white):",
        "input_bg_color": "Background color (black/red/green/yellow/blue/magenta/cyan/white):",
        "input_border_style": "Border style (round/double/single/bold/none):",
        "input_border_color": "Border color (black/red/green/yellow/blue/magenta/cyan/white):",
        "input_jump_page": "Input page number and press Enter to jump:",
        "bookmark_list": "Bookmark List",
        "input_remind_interval": "Reading reminder interval (minutes, 0=off):",
        "remind_msg": "You've been reading for {minutes} minutes, please rest your eyes!",
        "invalid": "Invalid input"
    }
}

def get_text(key, lang="zh"):
    return LANGS.get(lang, LANGS["zh"]).get(key, key)