#!/usr/bin/env bash

# ----------------------------------------------------------------------------------- #
echo "Changeing OS Settings ..."
# ----------------------------------------------------------------------------------- #

#调整每一列显示图标数量，12表示每一列显示12个，数字部分可根据个人喜好进行设置。
defaults write com.apple.dock springboard-columns -int 12
#调整多少行显示图标数量，这里我用的是6，数字部分你也可以改成8或其他
defaults write com.apple.dock springboard-rows -int 6
#重置ResetLaunchPad
defaults write com.apple.dock ResetLaunchPad -bool TRUE
#重启Dock
killall Dock

# ----------------------------------------------------------------------------------- #
echo "Starting Install New Softwares ..."
# ----------------------------------------------------------------------------------- #

#安装brew 软件
bash brew_logs
bash gem_logs
bash npm_logs
bash pip_logs

# ----------------------------------------------------------------------------------- #
echo "Starting Install SpaceVim Config ..."
# ----------------------------------------------------------------------------------- #

curl -sLf https://spacevim.org/cn/install.sh | bash

# ----------------------------------------------------------------------------------- #

# ----------------------------------------------------------------------------------- #
