#!/usr/bin/env bash

if [ ! -f ~/.myruntime ]; then
    echo "You need to create & input ~/.myruntime ..."
    vim ~/.myruntime
else
    MYRUNTIME=$(cat ~/.myruntime)
fi

echo "是否设置启动台行列，y|yes/n|no"
read choose
if [ "y" = "$choose" ] || [ "yes" = "$choose" ]; then
    # ----------------------------------------------------------------------------------- #
    echo "Changeing OS Settings ..."
    # ----------------------------------------------------------------------------------- #
    #调整每一列显示图标数量，12表示每一列显示12个，数字部分可根据个人喜好进行设置。
    defaults write com.apple.dock springboard-columns -int 12
    #调整多少行显示图标数量，这里我用的是6，数字部分你也可以改成8或其他
    defaults write com.apple.dock springboard-rows -int 6
    #重置ResetLaunchPad
    defaults write com.apple.dock ResetLaunchPad -bool TRUE
    #重启Dock
    killall Dock
fi

echo "是否安装oh-my-zsh，y|yes/n|no"
read choose
if [ "y" = "$choose" ] || [ "yes" = "$choose" ]; then
    # ----------------------------------------------------------------------------------- #
    echo "Starting Install Oh-My-Zsh ..."
    # ----------------------------------------------------------------------------------- #
    sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

    mv ~/.zshrc ~/.bak_zshrc

    ln -sf $MYRUNTIME/customs/configs/zshrc ~/.zshrc
fi

echo "是否安装bash-it，y|yes/n|no"
read choose
if [ "y" = "$choose" ] || [ "yes" = "$choose" ]; then
    # ----------------------------------------------------------------------------------- #
    echo "Starting Install Bash-it ..."
    # ----------------------------------------------------------------------------------- #
    cd ~ && git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it && bash ~/.bash_it/install.sh

    mv ~/.bashrc ~/.bak_bashrc
    mv ~/.bash_profile ~/.bak_bash_profile

    ln -sf $MYRUNTIME/customs/configs/bash_profile ~/.bashrc
    ln -sf $MYRUNTIME/customs/configs/bash_profile ~/.bash_profile
fi

echo "是否安装软件，y|yes/n|no"
read choose
if [ "y" = "$choose" ] || [ "yes" = "$choose" ]; then
    # ----------------------------------------------------------------------------------- #
    echo "Starting Install New Softwares ..."
    # ----------------------------------------------------------------------------------- #
    echo "安装brew 软件 ..."
    bash brew_logs
    echo "安装gem 软件 ..."
    bash gem_logs
    echo "安装npm 软件 ..."
    bash npm_logs
    echo "安装pip 软件 ..."
    bash pip_logs
    echo "安装go 软件 ..."
    bash go_logs
fi

echo "是否安装spacevim，y|yes/n|no"
read choose
if [ "y" = "$choose" ] || [ "yes" = "$choose" ]; then
    # ----------------------------------------------------------------------------------- #
    echo "Starting Install SpaceVim Config ..."
    # ----------------------------------------------------------------------------------- #
    ln -sf $MYRUNTIME/customs/configs/spacevim ~/.SpaceVim.d
    curl -sLf https://spacevim.org/cn/install.sh | bash
fi




# ----------------------------------------------------------------------------------- #
echo "是否使用配置文件，y|yes/n|no"
read choose
if [ "y" = "$choose" ] || [ "yes" = "$choose" ]; then
    mkdir -p ~/bak/config
    mv ~/.gitconfig ~/bak/
    ln -sf $MYRUNTIME/customs/configs/gitconfig                 ~/.gitconfig
    mv ~/.gitignore ~/bak/
    ln -sf $MYRUNTIME/customs/configs/gitignore                 ~/.gitignore
    mv ~/.zellij ~/bak/
    ln -sf $MYRUNTIME/customs/configs/zellij                    ~/.zellij
    mv ~/.tmux.conf ~/bak/
    ln -sf $MYRUNTIME/tmuxconfigs/yanghao.tmux.conf             ~/.tmux.conf
    mv ~/.wgetrc ~/bak/
    ln -sf $MYRUNTIME/customs/configs/wgetrc                    ~/.wgetrc
    mv ~/.hgignore ~/bak/
    ln -sf $MYRUNTIME/customs/configs/hgignore                  ~/.hgignore
    mv ~/.hgignore_global ~/bak/
    ln -sf $MYRUNTIME/customs/configs/hgignore_global           ~/.hgignore_global
    mv ~/.ls++.conf ~/bak/
    ln -sf $MYRUNTIME/customs/configs/ls++.conf                 ~/.ls++.conf
    mv ~/.myclirc ~/bak/
    ln -sf $MYRUNTIME/customs/configs/myclirc                   ~/.myclirc
    mv ~/.npmrc ~/bak/
    ln -sf $MYRUNTIME/customs/configs/npmrc                     ~/.npmrc
    mv ~/.p10k.zsh ~/bak/
    ln -sf $MYRUNTIME/customs/configs/p10k.zsh                  ~/.p10k.zsh
    mv ~/.pearrc ~/bak/
    ln -sf $MYRUNTIME/customs/configs/pearrc                    ~/.pearrc
    mv ~/.procs.toml ~/bak/
    ln -sf $MYRUNTIME/customs/configs/procs.toml                ~/.procs.toml
    mv ~/.xonshrc ~/bak/
    ln -sf $MYRUNTIME/customs/configs/xonshrc                   ~/.xonshrc
    mv ~/.starship ~/bak/
    ln -sf $MYRUNTIME/customs/configs/starship                  ~/.starship
    mv ~/.zshenv ~/bak/
    ln -sf $MYRUNTIME/customs/configs/zshenv                    ~/.zshenv
    mv ~/.zprofile ~/bak/
    ln -sf $MYRUNTIME/customs/configs/zprofile                  ~/.zprofile
    mv ~/.yarnrc ~/bak/
    ln -sf $MYRUNTIME/customs/configs/yarnrc                    ~/.yarnrc
    mv ~/.yabairc ~/bak/
    ln -sf $MYRUNTIME/customs/configs/yabairc                   ~/.yabairc
    mv ~/.skhdrc ~/bak/
    ln -sf $MYRUNTIME/customs/configs/skhdrc                    ~/.skhdrc
    mv ~/.fzf.zsh ~/bak/
    ln -sf $MYRUNTIME/customs/configs/fzf.zsh                   ~/.fzf.zsh
    mv ~/.fzf.bash ~/bak/
    ln -sf $MYRUNTIME/customs/configs/fzf.bash                   ~/.fzf.bash
    mv ~/.p10k.zsh ~/bak/
    cp $MYRUNTIME/customs/configs/p10k.zsh                      ~/.p10k.zsh
    mv ~/.czrc ~/bak/
    ln -sf $MYRUNTIME/customs/configs/czrc                      ~/.czrc
    
    
    
    mv ~/.config/zellij ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/zellij                    ~/.config/zellij
    mv ~/.config/starship ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/starship/starship         ~/.config/starship
    mv ~/.config/starship.toml ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/starship/starship.toml    ~/.config/starship.toml
    mv ~/.config/bat ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/bat                       ~/.config/bat
    mv ~/.config/ranger ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/ranger                    ~/.config/ranger
    mv ~/.config/atuin ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/atuin                     ~/.config/atuin
    mv ~/.config/cheat ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/cheat                     ~/.config/cheat
    mv ~/.config/dnote ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/dnote                     ~/.config/dnote
    mv ~/.config/gitui ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/gitui                     ~/.config/gitui
    mv ~/.config/gobang ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/gobang                    ~/.config/gobang
    mv ~/.config/htop ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/htop                      ~/.config/htop
    mv ~/.config/http-prompt ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/http-prompt               ~/.config/http-prompt
    mv ~/.config/litecli ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/litecli                   ~/.config/litecli
    mv ~/.config/lsd ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/lsd                       ~/.config/lsd
    mv ~/.config/neofetch ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/neofetch                  ~/.config/neofetch
    mv ~/.config/pgcli ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/pgcli                     ~/.config/pgcli
    mv ~/.config/spotify-tui ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/spotify-tui               ~/.config/spotify-tui
    mv ~/.config/thefuck ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/thefuck                   ~/.config/thefuck
    mv ~/.config/vifm ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/vifm                      ~/.config/vifm
    mv ~/.config/wtf ~/bak/config/
    ln -sf $MYRUNTIME/customs/configs/wtf                       ~/.config/wtf
    mv ~/.config/kitty/kitty.conf                               ~/bak/config/
    mkdir ~/.config/kitty/
    ln -sf $MYRUNTIME/customs/configs/kitty.conf                ~/.config/kitty/kitty.conf
fi
# ----------------------------------------------------------------------------------- #
