set -gx PATH $PATH /opt/homebrew/bin
set -gx PATH $PATH /Users/yanghao/Library/Python/3.8/bin
set -gx PATH $PATH /opt/homebrew/opt/icu4c/bin
set -gx PATH $PATH /opt/homebrew/opt/grep/bin
set -gx PATH $PATH /opt/homebrew/bin
set -gx PATH $PATH /Users/yanghao/data/data/.runtime//customs/bin
set -gx PATH $PATH /Users/yanghao/bin
set -gx PATH $PATH /usr/local/bin
set -gx PATH $PATH /sbin
set -gx PATH $PATH /usr/sbin
set -gx PATH $PATH /bin
set -gx PATH $PATH /usr/bin
set -gx PATH $PATH /opt/homebrew/opt/python/bin
set -gx PATH $PATH /opt/homebrew/opt/macvim/bin
set -gx PATH $PATH /usr/local/bin
set -gx PATH $PATH /Users/yanghao/data/data/.runtime//customs/bin/ssh-auto-login/auto_gen
set -gx PATH $PATH /Users/yanghao/go-develop/bin
set -gx PATH $PATH /opt/homebrew/opt/go/libexec/bin
set -gx PATH $PATH ~/.yarn/bin
set -gx PATH $PATH /Users/yanghao/.SpaceVim/bin
set -gx PATH $PATH /opt/homebrew/opt/sphinx-doc/bin
set -gx PATH $PATH /opt/homebrew/sbin
set -gx PATH $PATH /usr/local/bin
set -gx PATH $PATH /usr/bin
set -gx PATH $PATH /bin
set -gx PATH $PATH /usr/sbin
set -gx PATH $PATH /sbin
set -gx PATH $PATH /Library/Apple/usr/bin
set -gx PATH $PATH /Users/yanghao/.oh-my-zsh/custom/plugins/git-extra-commands/bin
set -gx PATH $PATH /opt/homebrew/opt/fzf/bin