fish_add_path ~/Library/Python/3.9/bin
fish_add_path ~/Library/Python/3.8/bin
fish_add_path /opt/homebrew/opt/icu4c/bin
fish_add_path /opt/homebrew/opt/grep/bin
fish_add_path /opt/homebrew/bin
fish_add_path ~/data/data/.runtime//customs/bin
fish_add_path ~/bin
fish_add_path /usr/local/bin
fish_add_path /sbin
fish_add_path /usr/sbin
fish_add_path /bin
fish_add_path /usr/bin
fish_add_path /opt/homebrew/opt/python/bin
fish_add_path /opt/homebrew/opt/macvim/bin
fish_add_path /usr/local/bin
fish_add_path ~/data/data/.runtime//customs/bin/ssh-auto-login/auto_gen
fish_add_path ~/go-develop/bin
fish_add_path /opt/homebrew/opt/go/libexec/bin
fish_add_path ~/.yarn/bin
fish_add_path ~/.SpaceVim/bin
fish_add_path /opt/homebrew/opt/sphinx-doc/bin
fish_add_path /opt/homebrew/sbin
fish_add_path /usr/local/bin
fish_add_path /usr/bin
fish_add_path /bin
fish_add_path /usr/sbin
fish_add_path /sbin
fish_add_path /Library/Apple/usr/bin
fish_add_path ~/.oh-my-zsh/custom/plugins/git-extra-commands/bin
fish_add_path /opt/homebrew/opt/fzf/bin

set  -gx PATH "/opt/homebrew/bin:$PATH"
