#!/usr/bin/env bash

#### 引入我自己的配置：开始
MYRUNTIME=$(cat $HOME/.myruntime)
my_custom_sh=$MYRUNTIME/customs/my_shell

[[ -f $HOME/.customs.sh ]] && source $HOME/.customs.sh
#
go2 () {
	[ -d "$1" ] && cd "$1" || cd "$(dirname "$1")"
}
source $my_custom_sh/library/core/bzsh/core_library.bzsh
source $my_custom_sh/bash/bmy_changebg.bash
source $my_custom_sh/bash/bmy_other.bash
