#!/usr/bin/env bash
# Desc: Fzf自定义命令的帮助信息
readonly bold="\e[1m"
readonly reset="\e[0m"
readonly italic="\e[3m"
readonly gray="\e[30m"
readonly c="\e[1;36m"
readonly d="\e[1;37m"


readonly help_header="${bold}${c}[Help Infomation]${c}${reset}
${bold}${italic}F1${reset}              Help infomation (this page).  ${d}[can also use Ctrl-H]${d}${reset}
${bold}${italic}F2${reset}              Switch search types(All、Files、Directories、Hiddens、Images、Medias、Documents、Languages、Contents). [can also use Ctrl-F]
${bold}${italic}F3${reset}              Toggle select all. ${d}[can also use Ctrl-A]${d}${reset}
${bold}${italic}F4${reset}              Toggle show/hide the preview window. ${d}[can also use Ctrl-T]${d}${reset}
${bold}${italic}F5${reset}              Change to Preview bigger to view.
${bold}${italic}F6${reset}              Toggle sort. 
${bold}${italic}F7${reset}              Open selected by command _operator with file type. ${d}[can also use Ctrl-O]${d}${reset}
${bold}${italic}F8${reset}              Use selected command from _actioner to deal with file. ${d}[can also use Ctrl-U]${d}${reset}
${bold}${italic}F9${reset}              Page up.
${bold}${italic}F10${reset}             Page down.
${bold}${italic}F11${reset}             Long list to show all of lines (Unusual in some functions). ${d}[can also use Ctrl-L]${d}${reset}
${bold}${italic}F12${reset}             Copy. ${d}[can also use Ctrl-Y]${d}${reset}
${bold}${italic}/${reset}               Show the input window."


readonly help_bottom="
${bold}${italic}Ctrl-/${reset}          Change preview window size (Multiple styles).
${bold}${italic}Ctrl-S${reset}          Save result list to file $HOME/Desktop/fzf_save.log
${bold}${italic}OPTION-J${reset}        Scroll up in the preview window.
${bold}${italic}OPTION-K${reset}        Scroll down in the preview window.
${bold}${italic}OPTION-H${reset}        Scroll half page up in the preview window.
${bold}${italic}OPTION-L${reset}        Scroll half page down in the preview window.
${bold}${italic}OPTION-G${reset}        Scroll to the top of the preview window.
${bold}${italic}OPTION-;${reset}        Scroll to the bottom of the preview window.
${bold}${italic}OPTION-X${reset}        Exclude the selected items or the current item .
${bold}${italic}OPTION-T${reset}        Toggle track.
${bold}${italic}OPTION-/${reset}        Toggle show/hide the header window.
${bold}${italic}OPTION-.${reset}        Go to the previous of selected.
${bold}${italic}OPTION-,${reset}        Go to the next of selected.
${bold}${italic}SHIFT-UP${reset}        Go to the first line.
${bold}${italic}SHIFT-DOWN${reset}      Go to the last line.
${bold}${italic}SPACE${reset}           Toggle jump mode (jump by single character).
${bold}${italic}ESC${reset}             Exit. ${d}[can also use Ctrl-G or Ctrl-C]${d}${reset}"
