#!/usr/bin/env bash
# Desc: Fzf自定义命令的帮助信息
source $MYRUNTIME/customs/tools/functions_help/common_help
readonly help_infomation="${c}This help information use fzf to select git stash and operate.${reset}"
readonly help_content="${bold}${italic}CTRL-D${reset}      Compare storage and HEAD.
${bold}${italic}CTRL-B${reset}      Split storage into branches."
readonly help="${help_header}
${help_content}
${help_bottom}


${help_infomation}
"
echo -e "$help"