#!/usr/bin/env bash
# Desc: Fzf自定义命令的帮助信息
source $MYRUNTIME/customs/tools/functions_help/common_help
readonly help_infomation="${c}Use Fzf to list all files in the current directory and edit them after selecting them.${reset}"
readonly help_content="${bold}${italic}CTRL-R${reset}      Open
${bold}${italic}CTRL-E${reset}      Edit by nvim"
readonly help="${help_header}
${help_content}
${help_bottom}


${help_infomation}
"
echo -e "$help"