#!/usr/bin/env bash
# Desc: Fzf自定义命令的帮助信息
source $MYRUNTIME/customs/tools/functions_help/common_help
readonly help_infomation="${c}利用fzf和别人写的linux命令markdown进行搜索.${reset}"
readonly help_content="${bold}${italic}CTRL-R${reset}          Open the website to preview."
readonly help="${help_header}
${help_content}
${help_bottom}


${help_infomation}
"
echo -e "$help"
