#!/usr/bin/env bash
# Desc: Fzf自定义命令的帮助信息
readonly bold="\e[1m"
readonly reset="\e[0m"
readonly italic="\e[3m"
readonly gray="\e[30m"
readonly c="\e[1;36m"
readonly d="\e[1;37m"
readonly help="${bold}${c}[Help Infomation]${c}${reset}
${bold}${italic}CTRL-O${reset}      Edit
${bold}${italic}CTRL-Y${reset}      Copy
${bold}${italic}CTRL-T${reset}      Toggle show the preview window
${bold}${italic}/${reset}           Show input window (Esc/Enter/Ctrl-C to exit)
${bold}${italic}CTRL-S${reset}      Toggle sort
${bold}${italic}CTRL-V${reset}      Change to Preview bigger to view
${bold}${italic}CTRL-N${reset}      Page down
${bold}${italic}CTRL-P${reset}      Page up
${bold}${italic}CTRL-A${reset}      Toggle select all
${bold}${italic}CTRL-J${reset}      Scroll up in the preview window
${bold}${italic}CTRL-K${reset}      Scroll down in the preview window
${bold}${italic}CTRL-L${reset}      Long list to show all of lines (Unusual in some functions)
${bold}${italic}OPTION-.${reset}    Go to the previous of selected
${bold}${italic}OPTION-,${reset}    Go to the next of selected
${bold}${italic}SHIFT-UP${reset}    Go to the first line
${bold}${italic}SHIFT-DOWN${reset}  Go to the last line
${bold}${italic}CTRL-H${reset}      Help infomation (this page)
${bold}${italic}SPACE${reset}       Toggle jump mode (jump by single character)
${bold}${italic}ESC${reset}         Exit


${c}Use Fzf to list modified files in the current Git version file and diff.${reset}
"

echo -e "$help"