#!/usr/bin/env bash
# Desc: Fzf自定义命令的帮助信息
source $MYRUNTIME/customs/tools/functions_help/common_help
readonly help_infomation="${c}Use Fzf to list all Man's help information.${reset}"
readonly help_content="${bold}${italic}OPTION-C${reset}    Search by cheat
${bold}${italic}OPTION-M${reset}    Search by man
${bold}${italic}OPTION-R${reset}    Search by tldr
${bold}${italic}CTRL-O${reset}      Edit"
readonly help="${help_header}
${help_content}
${help_bottom}


${help_infomation}
"
echo -e "$help"