#!/usr/bin/env bash
# Desc: Fzf自定义命令的帮助信息
source $MYRUNTIME/customs/tools/functions_help/common_help
readonly help_infomation="${c}Use Fzf and Rg to search for keywords to get the list and the row where it is located. After selecting, vscode locates the row for editing.${reset}"
readonly help_content="${bold}${italic}CTRL-F${reset}      Search with fzf
${bold}${italic}CTRL-R${reset}      Search with ripgrep
${bold}${italic}CTRL-E${reset}      Edit by vscode"
readonly help="${help_header}
${help_content}
${help_bottom}


${help_infomation}
"
echo -e "$help"