#!/usr/bin/env bash
# Desc: Fzf自定义命令的帮助信息
readonly bold="\e[1m"
readonly reset="\e[0m"
readonly italic="\e[3m"
readonly gray="\e[30m"
readonly c="\e[1;36m"
readonly d="\e[1;37m"
readonly help="${bold}${c}[帮助信息]${c}${reset}
${bold}${italic}CTRL-O${reset}   预览全部
${bold}${italic}CTRL-Y${reset}   复制内容
${bold}${italic}CTRL-T${reset}   切换预览窗口
${bold}${italic}CTRL-S${reset}   切换排序
${bold}${italic}CTRL-N${reset}   下翻页
${bold}${italic}CTRL-P${reset}   上翻页
${bold}${italic}CTRL-A${reset}   全选/取消全选
${bold}${italic}CTRL-J${reset}   预览内容上滚动
${bold}${italic}CTRL-K${reset}   预览内容下滚动
${bold}${italic}CTRL-L${reset}   长列表显示(在某些函数中失效或异常显示)
${bold}${italic}OPTION-.${reset} 选中项目中跳转下一个
${bold}${italic}OPTION-,${reset} 选中项目中跳转上一个
${bold}${italic}F1${reset}       帮助信息 (this page)
${bold}${italic}ESC${reset}      退出


${c}利用Fzf列出所有自定义的alias命令别名,选中后执行.${reset}
"

echo -e "$help"