#!/usr/bin/env bash
#-----------------------------------------------------------#
echo "Tapping Taps Of Homebrew ..."
#-----------------------------------------------------------#
#[[[
brew tap beeftornado/rmtree     # 循环移除指令的仓库
brew tap homebrew/cask          # 「Casks」
brew tap homebrew/cask-fonts    # 字体仓库
brew tap homebrew/cask-versions # 历史版本软件包仓库
brew tap homebrew/core          # 「Formulae」
brew tap homebrew/services      # 服务指令仓库
brew tap homebrew/aliases
brew tap homebrew/homebrew-livecheck
brew tap homebrew/command-not-found
brew tap homebrew/bundle
brew tap shivammathur/php
brew tap shivammathur/extensions
brew tap neovim/neovim
brew tap cowsay-org/cowsay
brew tap denji/nginx
brew tap cjbassi/gotop
brew tap aykamko/tag-ag
brew tap federico-terzi/espanso
brew tap how2terminal/how2
brew tap koekeishiya/formulae
#]]]

#-----------------------------------------------------------#
echo "Installing Download Softwares ..."
#-----------------------------------------------------------#
#[[[
brew install curl
brew install wget
brew install burl
brew install aria2
#]]]
#-----------------------------------------------------------#
echo "Installing Libraries ..."
#-----------------------------------------------------------#
#[[[
brew install libass
brew install libassuan
brew install libav
brew install libbluray
brew install libbs2b
brew install libcaca
brew install libcbor
brew install libcerf
brew install libcouchbase
brew install libcroco
brew install libdap
brew install libde265
brew install libdnet
brew install libepoxy
brew install libev
brew install libevent
brew install libffi
brew install libfido2
brew install libftdi
brew install libgcrypt
brew install libgeotiff
brew install libgpg-error
brew install libgphoto2
brew install libgsm
brew install libheif
brew install libice
brew install libicns
brew install libiconv
brew install libidn
brew install libidn2
brew install libiscsi
brew install libksba
brew install liblqr
brew install libmagic
brew install libmaxminddb
brew install libmemcached
brew install libmetalink
brew install libmodplug
brew install libmpc
brew install libmpdclient
brew install libogg
brew install libomp
brew install libplist
brew install libpng
brew install libpq
brew install libpsl
brew install libpthread-stubs
brew install libquvi
brew install librdkafka
brew install libressl
brew install librsvg
brew install librttopo
brew install libsamplerate
brew install libserdes
brew install libsigc++
brew install libsigc++@2
brew install libsm
brew install libsndfile
brew install libsodium
brew install libsoup
brew install libsoxr
brew install libspatialite
brew install libssh
brew install libssh2
brew install libtasn1
brew install libtermkey
brew install libtiff
brew install libtool
brew install libunistring
brew install libusb
brew install libusb-compat
brew install libusbmuxd
brew install libuv
brew install libvidstab
brew install libvirt
brew install libvo-aacenc
brew install libvorbis
brew install libvpx
brew install libvterm
brew install libwbxml
brew install libwebsockets
brew install wtf
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxft
brew install libxkbcommon
brew install libxml2
brew install libxmu
brew install libxp
brew install libxrender
brew install libxt
brew install libyaml
brew install libzip
brew install giflib
brew install ghc
brew install ghi
#]]]

#-----------------------------------------------------------#
echo "Installing Languages ..."
#-----------------------------------------------------------#
#[[[
brew install llvm
brew install go
brew install python
brew install cython
brew install node
brew install erlang
brew install php@5.6
brew install php@7.0
brew install php@7.1
brew install php@7.2
brew install php@7.3
brew install php@7.4
brew install php
brew install ruby
brew install ruby-build
brew install ruby-install
brew install rust
brew install rustup-init
brew install java
brew install bison
brew install boost
brew install kotlin
brew install expect
brew install lua
brew install lua52
brew install lua@5.1
brew install luajit
brew install luarocks
brew install peco
brew install perl
brew install perl@5.18
brew install ocaml
brew install v8
brew install maven
brew install phantomjs
brew install cifer
brew install doxygen
brew install swift

#]]]

#-----------------------------------------------------------#
echo "Installing Language Supports ..."
#-----------------------------------------------------------#
#[[[
brew install imagemagick
brew install imagesnap
brew install imap-uw
brew install gd
brew install geoip
brew install geos
brew install gettext
brew install gflags
brew install glib
brew install glib-networking
brew install glib-openssl
brew install glibmm
brew install grpc
brew install icoutils
brew install icu4c
brew install id3tool
brew install idutils
brew install gsasl
brew install gsl
brew install grc
brew install pcre
brew install pcre2
brew install protobuf
brew install apr
brew install openjdk
brew install openjdk@11
brew install openjdk@8
brew install pickle
brew install pidcat
brew install nushell
brew install jmeter
#]]]

#-----------------------------------------------------------#
echo "Installing Language Support Extensions ..."
#-----------------------------------------------------------#
#[[[
brew install imap@5.6
brew install imap@7.0
brew install imap@7.1
brew install imap@7.2
brew install imap@7.3
brew install imap@7.4
brew install imagick@5.6
brew install imagick@7.0
brew install imagick@7.1
brew install imagick@7.2
brew install imagick@7.3
brew install imagick@7.4
brew install swoole@5.6
brew install swoole@7.0
brew install swoole@7.1
brew install swoole@7.2
brew install swoole@7.3
brew install swoole@7.4
brew install pcov@7.1
brew install pcov@7.2
brew install pcov@7.3
brew install pcov@7.4
brew install protobuf@3.7
brew install protobuf@5.6
brew install protobuf@7.0
brew install protobuf@7.1
brew install protobuf@7.2
brew install protobuf@7.3
brew install protobuf@7.4
brew install xdebug@5.6
brew install xdebug@7.0
brew install xdebug@7.1
brew install xdebug@7.2
brew install xdebug@7.3
brew install xdebug@7.4
#]]]

#-----------------------------------------------------------#
echo "Installing Language Support Libraries ..."
#-----------------------------------------------------------#
#[[[
brew install php-code-sniffer
brew install php-cs-fixer
brew install phplint
brew install phpmd
brew install phpstan
brew install phpunit
brew install brew-php-switcher
brew install bench
brew install bzip2
brew install pkg-config
brew install pipenv
brew install nodenv
brew install pyenv
brew install jenv
brew install nvm
brew install gdb
brew install gdbm
brew install freetype
brew install p7zip
brew install gzip
brew install faac
brew install procs
brew install base64
brew install xmlstarlet
brew install utf8cpp
brew install utf8proc
brew install unbound
brew install uni2ascii
brew install unibilium
brew install unison
brew install unixodbc
brew install upx
brew install swig
brew install swig@3

#]]]

#-----------------------------------------------------------#
echo "Installing System Depends ..."
#-----------------------------------------------------------#
#[[[
brew install cmake
brew install make
brew install bsdmake
brew install makedepend
brew install ninja
brew install gcc
brew install gawk
brew install gnu-getopt
brew install gnu-indent
brew install gnu-sed
brew install gnu-tar
brew install gnu-which
brew install gnupg
brew install gnuplot
brew install gnutls
brew install awk
brew install bash
brew install fish
brew install zsh
brew install autoconf
brew install automake
brew install global
brew install grep
brew install ripgrep
brew install fd
brew install ipv6calc
brew install ipv6toolkit
brew install jemalloc
brew install mcrypt
brew install binwalk
brew install qt
brew install maxwell
brew install coreutils
brew install dex2jar
brew install unzip
brew install czmq
brew install dbus
brew install dcraw
brew install deployer
brew install double-conversion
brew install ack
brew install axel
brew install zopfli
brew install zsh-completions
brew install zsh-syntax-highlighting
brew install zshdb
brew install zstd
brew install navi
brew install dialog
brew install zimg
brew install zlib
brew install zbar
brew install xvid
brew install xxhash
brew install xz
brew install xpdf
brew install syncthing
brew install sysbench
#]]]

#-----------------------------------------------------------#
echo "Installing Services Softwares ..."
#-----------------------------------------------------------#
#[[[
brew install nginx-full --with-rtmp-module --with-realip --with-http2 --with-stream --with-flv --with-mp4 --with-gunzip --with-debug --with-upload-module --with-stream-geoip --with-vod-module --with-redis2-module --with-mp4-h264-module --cc=gcc
brew install leveldb
brew install mysql
brew install mysql-client
brew install mysql-search-replace
brew install mysql@5.7
brew install beanstalkd
brew install memcached
brew install redis
brew install elasticsearch
brew install httpd
brew install --build-from-source kafka
brew install --build-from-source leveldb
brew install --build-from-source rabbitmq-c
brew install hbase
brew install dnsmasq
brew install glances
brew install zookeeper
brew install zeromq
brew install tomcat
#]]]

#-----------------------------------------------------------#
echo "Installing Useful Commands ..."
#-----------------------------------------------------------#
#[[[
brew install bash-completion@2
brew install pipx
brew install bat
brew install eth-p/software/bat-extras
brew install ccat
brew install cheat
brew install binutils
brew install colordiff
brew install ctags
brew install fzf
brew install zoxide
brew install Rasukarusan/tap/fzf-bluetooth-connect
brew install autojump
brew install dark-mode
brew install dash
brew install exa
brew install selecta
brew install sk
brew install diff-so-fancy
brew install diffutils
brew install pkgdiff
brew install icdiff
brew install wdiff
brew install chruby
brew install chruby-fish
brew install asdf
brew install docker
brew install docker-compose
brew install docker-machine
brew install fasd
brew install google-sparsehash
brew install googler
brew install gotop
brew install gotty
brew install dcd
brew install vim
brew install neovim
brew install macvim
brew install ed
brew install editorconfig
brew install fontconfig
brew install git
brew install git-annex
brew install git-extras
brew install git-flow
brew install git-flow-avh
brew install git-lfs
brew install git-town
brew install htop
brew install iftop
brew install hub
brew install highlight
brew install mercurial
brew install mycli
brew install automysqlbackup
brew install m-cli
brew install pgcli
brew install mytop
brew install jq
brew install composer
brew install http_load
brew install httpstat
brew install less
brew install lazygit
brew install dos2unix
brew install lesspipe
brew install links
brew install neofetch
brew install net-snmp
brew install ncdu
brew install netcat
brew install netcdf
brew install netpbm
brew install nettle
brew install nghttp2
brew install ghostscript
brew install asciidoc
brew install man2html
brew install mandoc
brew install docbook
brew install docbook-xsl
brew install docutils
brew install cabal-install
brew install pango
brew install cairo
brew install cairomm
brew install clingo
brew install chromaprint
brew install platformio
brew install antigen
brew install cloc
brew install capnp
brew install cscope
brew install cunit
brew install pidof
brew install pigz
brew install pinentry
brew install pixman
brew install archey
brew install argon2
brew install arpack
brew install asciinema
brew install aspell
brew install astyle
brew install ffsend
brew install lolcat
brew install sebglazebrook/aliases/aliases
brew install hr
brew install starship
brew install jesseduffield/lazydocker/lazydocker
brew install sachaos/todoist/todoist
brew install ctop
brew install nvie/tap/git-toolbelt
brew install fswatch
brew install hyperfine
brew install --HEAD wvanlint/twf/twf
brew install mdcat
brew install laggardkernel/tap/iterm2-zmodem
brew install you-get
brew install z
brew install hstr
brew install mas
brew install whatmask
brew install when
brew install winetricks
brew install wmctrl
brew install woff2
brew install tig
brew install tldr
brew install thefuck
brew install tmate
brew install tmux
brew install tmux-xpanes
brew install tmuxinator-completion
brew install todo-txt
brew install toilet
brew install trash
brew install tree
brew install ttygif
brew install ttyrec
brew install task
brew install taskd
brew install tasksh
brew install tbb
brew install tcl-tk
brew install tcpflow
brew install tcpreplay
brew install tcptrace
brew install telnet
brew install terminal-notifier
brew install the_platinum_searcher
brew install the_silver_searcher

#]]]

#-----------------------------------------------------------#
echo "Installing Cast Softwares ..."
#-----------------------------------------------------------#
#[[[
brew install iina
brew install osxfuse
brew install xquartz
brew install bork
brew install cmatrix
brew install confuse
brew install cpanminus
brew install --cask he3-app/he3/he3
#]]]

#-----------------------------------------------------------#
echo "Installing Fonts ..."
#-----------------------------------------------------------#
#[[[
brew install font-fira-mono
brew install font-inconsolata
brew install font-fira-code-nerd-font
brew install font-hack-nerd-font
brew install --cask font-hack-nerd-font
#]]]

#-----------------------------------------------------------#
echo "Installing Other Softwares ..."
#-----------------------------------------------------------#
#[[[
brew install fortune
brew install sl
brew install cowsay
brew install cowsay-apj
brew install figlet
brew install mtmr
brew install corkscrew
brew install ffmpeg --with-fdk-aac --with-fontconfig --with-freetype --with-frei0r --with-game-music-emu --with-libass --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-librsvg --with-libsoxr --with-libssh --with-libvidstab --with-libvorbis --with-libvpx --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-rubberband --with-sdl2 --with-snappy --with-speex --with-tesseract --with-theora --with-tools --with-two-lame --with-wavpack --with-webp --with-x265 --with-xz --with-zeromq --with-zimg
brew install eg-examples
#]]]

####unfinished

brew install eigen
brew install elixir
brew install epsilon
brew install epstool
brew install espeak
brew install exenv
brew install exiftool
brew install expat
brew install extract_url
brew install fcrackzip
brew install fdk-aac
brew install file-formula
brew install findutils
brew install flac
brew install flock
brew install flow
brew install fltk
brew install foremost
brew install fpp
brew install freetds
brew install freexl
brew install frei0r
brew install fribidi
brew install fzy
brew install game-music-emu
brew install glide
brew install glog
brew install glpk
brew install gmp
brew install go-md2man
brew install gobject-introspection
brew install goby
brew install gpatch
brew install gperftools
brew install gpg-agent
brew install graphicsmagick
brew install graphite2
brew install graphviz
brew install groff
brew install guile
brew install harfbuzz
brew install hashpump
brew install hdf5
brew install hugo
brew install hwloc
brew install hydra
brew install hyperspec
brew install ilmbase
brew install imessage-ruby
brew install imlib2
brew install inetutils
brew install inlets
brew install intltool
brew install ipcalc
brew install irssi
brew install isl
brew install jam
brew install jansson
brew install jasper

brew install john
brew install jpeg
brew install json-c
brew install json-glib
brew install jsoncpp
brew install jsonpp
brew install kafka
brew install kafkacat
brew install keychain
brew install knock
brew install krb5
brew install lame

brew install ldns
brew install leptonica

brew install little-cms
brew install little-cms2

brew install lrzsz
brew install lsd
brew install lynx
brew install lz4
brew install lzip
brew install lzlib
brew install lzo
brew install m4
brew install mackup

brew install mapnik

brew install mecab
brew install megatools
brew install meson
brew install metis
brew install mhash
brew install midnight-commander
brew install minizip
brew install moreutils
brew install mosh
brew install mosquitto
brew install most
brew install mpc
brew install mpfr
brew install msgpack
brew install mtr
brew install multimarkdown
brew install mupdf-tools
brew install narwhal
brew install nasm
brew install ncurses
brew install nkf
brew install nmap
brew install nnn
brew install npth
brew install nspr
brew install nss
brew install numpy
brew install nyancat

brew install ocamlbuild
brew install octave
brew install oniguruma
brew install opam
brew install open-mpi
brew install openblas
brew install opencc
brew install openconnect
brew install opencore-amr
brew install opencv
brew install openexr
brew install openh264
brew install openjpeg
brew install openldap
brew install openmotif
brew install openssh
brew install openssl@1.1
brew install opus
brew install ossp-uuid
brew install osxutils
brew install p11-kit

brew install par
brew install pdflib-lite

brew install platypus
brew install plotutils
brew install pngcheck
brew install podofo
brew install poppler
brew install popt
brew install portaudio
brew install postgresql
brew install potrace
brew install pre-commit
brew install proctools
brew install proj

brew install qhull
brew install qrencode
brew install qrupdate
brew install qscintilla2

brew install quvi
brew install rabbitmq
brew install rabbitmq-c
brew install ragel
brew install ranger
brew install rav1e
brew install rbenv
brew install rcm
brew install re2
brew install re2c
brew install readline
brew install reattach-to-user-namespace
brew install remind
brew install rename
brew install rhino
brew install rrdtool
brew install rsync
brew install rtmpdump
brew install rubberband

brew install s-lang
brew install s-search
brew install sane-backends
brew install scons
brew install screen
brew install screenfetch
brew install screenresolution
brew install scrypt
brew install sdb
brew install sdl
brew install sdl2
brew install shared-mime-info
brew install shellcheck
brew install shfmt
brew install shpotify
brew install siege
brew install sip
brew install smartmontools
brew install snappy
brew install socat
brew install source-highlight
brew install spark
brew install speedtest-cli
brew install speex
brew install speexdsp
brew install sphinx
brew install sphinx-doc
brew install sqlite
brew install sqlmap
brew install squid
brew install srt
brew install ssdeep
brew install ssh-copy-id
brew install sshfs
brew install startup-notification
brew install stoken
brew install stow
brew install subversion
brew install suite-sparse
brew install sundials
brew install swiftlint
brew install szip
brew install t1lib
brew install ta-lib
brew install tesseract
brew install texi2html
brew install texinfo
brew install theora
brew install tidy-html5
brew install two-lame
brew install uchardet
brew install ucl
brew install ucspi-tcp
brew install ufraw
brew install unar
brew install urlview
brew install vala
brew install veclibfort
brew install vifm
brew install vtk
brew install watch
brew install watchman
brew install wavpack
brew install webkit2png
brew install webp
brew install wemux
brew install wrk
brew install wxmac
brew install x264
brew install x265
brew install xbitmaps
brew install xcb-util
brew install xctool
brew install xdot
brew install xerces-c
brew install xkeyboardconfig
brew install xmlto
brew install xonsh
brew install xorgproto
brew install yajl
brew install pick
brew install desk
brew install httpie
brew install dbcli/tap/pgcli
brew install micro
brew install docui
brew install grafana
brew install progress
brew install hexyl
brew install fx
brew install zenity
brew install atuin
brew install tag-ag
brew install pandoc
brew install bastet
brew install chafa
brew install xsv
brew install create-dmg
brew install glow
brew install wtfutil
brew install zellij
brew install bottom
brew install git-delta
brew install broot
brew install xplr
brew install bpytop
brew install just
brew install nb
brew install lf
brew install tealdeer
brew install espanso
brew install how2
brew install difftastic
brew install sd
brew install dust
brew install duf
brew install dog
brew install antibody
brew install curlie
brew install xh
brew install delta
brew install mcfly
brew install choose
brew install vivid
brew install pstree
brew install mpv
brew install dive
brew install tako8ki/tap/gobang
brew install gitui
brew install jesseduffield/lazynpm/lazynpm
brew install veeso/termscp/termscp
brew install termshark
brew install cointop
brew install plow
brew install ryo-ma/lazyhub/lazyhub
brew install lsix
brew install media-info
brew install atool
brew install docx2txt
brew install skhd
brew install yabai
brew install qlcolorcode
brew install qlstephen
brew install qlmarkdown
brew install quicklook-json
brew install qlimagesize
brew install suspicious-package
brew install apparency
brew install quicklookase
brew install qlvideo
brew install wireguard-tools
brew install helix
brew install mprocs
brew install loc
brew install prettyping
brew install rs/tap/jplot
brew install wordnet
brew install scc
brew install tre-command
brew install howdoi
brew install rich
brew install goaccess
brew install gum
brew install pop
brew install charmbracelet/tap/mods
brew install charmbracelet/tap/wishlist
brew install vhs
brew install charmbracelet/tap/skate
brew install MisterTea/et/et
brew install --cask alt-tab
brew install eza
brew install maccy
brew install pv
brew install kyu08/tap/fzf-make
brew install forgit
brew install code-minimap
brew install --cask keycastr
brew install jpe90/clp/clp
brew install version-fox/tap/vfox
brew install dsq
brew install tssh
brew install restic
brew install stylua
brew install git-chglog/git-chglog/git-chglog
brew install --cask superproductivity
brew install cog
brew install hurl
brew install tailspin
brew install bruno
brew install sad
brew install ugit
brew install lux
brew install bearer/tap/bearer
brew install timg
brew install supabase/tap/supabase
brew install harelba/q/q
brew install mise
brew install mkcert
brew install nss
brew install doggo
brew install rm-improved
brew install tre-command
brew install khal
brew install dduan/formulae/ea
brew install tokei
brew install duti
brew install viu # 缩率图查看器
brew install csvtk
brew install audio-fingerprint parallel tesseract whisper
brew install --no-quarantine syntax-highlight
brew install pup
