#!/usr/bin/env sh
##
## Copy from https://www.joshmedeski.com/posts/blazing-fast-window-management-on-macos/
##

#sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"


# global settings
yabai -m config 							\
mouse_follows_focus          off			\
focus_follows_mouse          off			\
window_origin_display        default		\
window_placement             second_child	\
window_topmost               off			\
window_shadow                on				\
window_opacity               on				\
window_animation_duration    0.25         	\
window_opacity_duration      0.25			\
active_window_opacity        0.90			\
normal_window_opacity        0.50			\
window_border_width          4				\
window_border_radius         12           	\
window_border_blur           on           	\
window_border_hidpi          on           	\
window_border                on				\
active_window_border_color   0xff775759		\
normal_window_border_color   0xff555555		\
insert_feedback_color        0xffd75f5f		\
split_ratio                  0.50			\
auto_balance                 off			\
mouse_modifier               fn				\
mouse_action1                move			\
mouse_action2                resize			\
mouse_drop_action            swap			\
layout                       float			\
top_padding                  5				\
bottom_padding               5				\
left_padding                 5 				\
right_padding                5				\
window_gap                   5 				\
external_bar                main:10:0 		\
external_bar                all:10:10

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pika$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="^Music$" manage=off

# window rules
yabai -m rule --add app="^Mail$" space=mail
yabai -m rule --add app="^Safari$" space=web
yabai -m rule --add app="^Notes$" space=notes
yabai -m rule --add app="^ida64$" space=re
yabai -m rule --add app="^Transmission$" space=media
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^Discord$" space=social grid=1:1:0:0:1:1 manage=off
yabai -m rule --add app="^Steam$" space=games manage=off
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" manage=off
yabai -m rule --add app="^mpv$" manage=off border=off sticky=on layer=above opacity=1.0 grid=8:8:6:0:2:2

# mission-control desktop labels
yabai -m space 1 --label code
yabai -m space 2 --label mail
yabai -m space 3 --label web
yabai -m space 4 --label notes
yabai -m space 5 --label re
yabai -m space 6 --label media
yabai -m space 7 --label social
yabai -m space 8 --label games


echo "yabai configuration loaded.."
