#!/bin/zsh
# File              : .zshrc
# Date              : 28.02.2024
# Last Modified Date: 28.02.2024
# Fig pre block. Keep at the top of this file.
#[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
#zmodload zsh/zprof

autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH="/opt/homebrew/sbin:/opt/homebrew/bin:$PATH"

source $(cat $HOME/.myruntime)/customs/my_shell/rcfile

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

#GITSTATUS_LOG_LEVEL=DEBUG


# Fig post block. Keep at the bottom of this file.
#[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"