#!/usr/bin/env bash
######################################################
# This rcfile and custom settings can be only used for
# ZSH or BASH
# Usage: In your ~/.bashrc or ~/.zshrc
#    source $MYRUNTIME/customs/my_shell/rcfile
#
######################################################
export MYRUNTIME=$(cat ~/.myruntime)

curshell() {
    if [ -n "$ZSH_VERSION" ]; then
        echo "zsh"
    elif [ -n "$BASH_VERSION" ]; then
        echo "bash"
    elif [ -n "$FISH_VERSION" ]; then
        echo "fish"
    else
        echo "Unknow"
    fi
}

curterm() {
    TMPCURTERM=$(env | grep 'TERM_PROGRAM=' | sed 's/TERM_PROGRAM=//')
    CURTERM="Unknow"
    if [ "$TMPCURTERM" = "iTerm.app" ]; then
        CURTERM='iTerm'
    elif [ "$TMPCURTERM" = "Apple_Terminal" ]; then
        CURTERM='Terminal'
    fi
    echo $CURTERM
}

curPanel() {
  panel="shell"
  if [ ! -z "$STY" ]; then
    panel="screen"
  elif [ ! -z "$TMUX" ]; then
    panel="tmux"
  fi
  echo $panel;
}

export nowshell=$(curshell)
export nowterm=$(curterm)
export nowpanel=$(curPanel)
source $MYRUNTIME/customs/my_shell/${nowshell}/custom_shrc
[[ -f $MYRUNTIME/customs/my_shell/customs.sh ]] && source $MYRUNTIME/customs/my_shell/customs.sh
