#!/bin/zsh

function _fuzzy-fs-list-recent-dir {
    local field=list-rencent-dir
    # if you use z to jump between directories
    if {which _z &> /dev/null}; then
        if {which gsed &> /dev/null}; then
            _z -l 2>&1 | tac | grep "/.*" -o | gsed "s/^/$recent_dir_icon /"
        else
            _z -l 2>&1 | tac | grep "/.*" -o | sed "s/^/$recent_dir_icon /"
        fi
    fi
    # if you use autojump
    if {which autojump &> /dev/null}; then
        if {which ghead &> /dev/null}; then
            autojump -s | sed -E '/^___/q;s/[0-9]*\.[0-9]*:[[:space:]]*//;' | ghead -n-1 | sed "s/^/$recent_dir_icon /"
        else
            autojump -s | sed -E '/^___/q;s/[0-9]*\.[0-9]*:[[:space:]]*//;' | head -n-1 | sed "s/^/$recent_dir_icon /"
        fi
    fi
}
